### ISSUE TITLE
firstVideoKeyFrame、firstAudioKeyFrame疑问？

### ISSUE THREAD

**Issue by wuli07101** [gqf2008/bbllive#10]
1、firstVideoKeyFrame、firstAudioKeyFrame一直不更新
if s.Type == RTMP_MSG_VIDEO && s.IFrame() && m.firstVideoKeyFrame == nil {
        log.Info(">>>>", s)
        m.firstVideoKeyFrame = s
        m.streamid = s.StreamId
        m.lock.Unlock()
        return
    }
    if s.Type == RTMP_MSG_AUDIO && m.firstAudioKeyFrame == nil {
        log.Info(">>>>", s)
        m.firstAudioKeyFrame = s
        m.lock.Unlock()
        return
    }
    if s.Type == RTMP_MSG_AMF_META && m.metaData == nil {
        log.Info(">>>>", s)
        m.metaData = s
        m.lock.Unlock()
        return
    }

是不是更新为最新的会更好，每个客户端拉流时都会推送firstVideoKeyFrame、firstAudioKeyFrame，这数据不会是旧的吗？

**Comment by gqf2008** [comment]
flv的第一帧是音视频的编解码信息，不包括音视频数据
