### ISSUE TITLE
如果媒体没有音频第一关键信息，会崩溃

### ISSUE THREAD

**Issue by parchk** [gqf2008/bbllive#11]
![qq 20160926112238](https://cloud.githubusercontent.com/assets/12369932/18821753/b20a9b10-83db-11e6-9f41-d265ec6d65a4.png)

**Comment by wuli07101** [comment]
做个空判断即可，但是做了判断后，有另一个问题，就是播放后要等很久动画才动，目前我把firstVideoKeyFrame改成实时更新后就正常了

**Comment by parchk** [comment]
- @wuli07101 firstVideoKeyFrame不能实时更新的吧，第一关键帧是带信息的，跟后面的关键帧是不一样的。

**Comment by wuli07101** [comment]
更新为上一个GOP的关键帧。目前下发client是延了一个关键帧
if s.IFrame() && m.gop.Len() > 0 {
		gop := m.gop
		m.list = append(m.list, gop.idx)
		m.cache[gop.idx] = gop
		log.Info("Gop", m.name, gop.idx, gop.Len(), len(m.list))
		m.gop = &MediaGop{# **gop.idx + 1**, []*MediaFrame{s}, m.firstVideoKeyFrame, m.firstAudioKeyFrame, m.metaData}
		// m.gop.chunk.wchunks = gop.chunk.wchunks
		// m.gop.freshChunk.writeMetadata(m.metaData)
		// m.gop.freshChunk.writeFullVideo(m.firstVideoKeyFrame)
		// m.gop.freshChunk.writeFullAudio(m.firstAudioKeyFrame)
		// m.gop.freshChunk.writeFullVideo(s)
		// m.gop.chunk.writeVideo(s)
		m.lock.Unlock()
		select {
		case m.notify <- &# **gop.idx**:
		default:
			err = ErrBufferFull
		}
		return
	}

**Comment by parchk** [comment]
@wuli07101 GOP cache就是缓存GOP，跟你说的不动，和更新firstvidoframe不是一个事，除非你不想用gop cache.不太理解你的修改

**Comment by gqf2008** [comment]
@all 离开这个行业了，供大家学习考
