### ISSUE TITLE
firstVideoFrame关键帧需要动态修改

### ISSUE THREAD

**Issue by parchk** [gqf2008/bbllive#12]
当发生画面旋转分辨率修改的信息时，需要动态修改firstVideoFrame，否则会花屏，类似我图片上代码的改动。
![qq 20161017163033](https://cloud.githubusercontent.com/assets/12369932/19430504/0e0d3632-9487-11e6-9ece-4130821643fd.png)

**Comment by gqf2008** [comment]
离开这个行业了，供大家学习考

**Comment by gqf2008** [comment]
发pr上来
