### ISSUE TITLE
我测试的结果是，播放的视频一卡一卡的，使用其他rtmp服务器都正常，不卡

### ISSUE THREAD

**Issue by chengziqing** [gqf2008/bbllive#13]
如题

**Comment by gqf2008** [comment]
推流软件是哪个？

**Comment by sheepbao** [comment]
我测试的时候也是一卡一卡的，推流用ffmpeg， 播放用ffplay，我用ffplay开log看了一下，ffplay接收数据就是一秒一次，有空再看看源码是怎么回事，估计是网络发数据的代码有问题

**Comment by gqf2008** [comment]
我怀疑是你的编码参数不对 一卡一卡很可能是时间戳不对

**Comment by sheepbao** [comment]
你要怀疑ffmpeg吗？而且我用别人rtmp服务器就不会有这样情况，
我的推流命令：
`ffmpeg -re -i test.flv -c copy -f flv rtmp://localhost/live/test`,
 播放：
`ffplay rtmp://localhost/live/test`。

**Comment by gqf2008** [comment]
不要用copy 重新编码后再推
