### ISSUE TITLE
测试时发现Heap越来越多，占用内存也在不停增多

### ISSUE THREAD

**Issue by GinRyan** [gqf2008/bbllive#14]
现有一个测试出现的情况：
1、测试环境是Windows
2、使用ffmpeg推流4个不同的mp4文件，一共4个推流进程

测试现象是：
在  http://127.0.0.1:6060/debug/pprof/
中查看内存堆信息，Heap不停增长，在任务管理器中程序占用的内存由几MB开始增长到几十M，播放一段时间后逐渐逼近100MB
这是否属于正常现象？
另外，Heap当中大部分是rtmp_socket.go:399 ，是否存在没有回收的内存？

**Comment by gqf2008** [comment]
可能存在内存泄漏，测并发可以用srs-bench工具跑压力
