### ISSUE TITLE
sendFullAudio错误

### ISSUE THREAD

**Issue by wuli07101** [gqf2008/bbllive#5]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x48ca5e]

goroutine 34 [running]:
panic(0x80cd20, 0xc82000a100)
    /usr/local/go/go-go1.6/src/runtime/panic.go:464 +0x3e6
bbllive/rtmp.sendFullAudio(0xc820128300, 0x0, 0x0, 0x0)
    /data1/go/bbllive/src/bbllive/rtmp/rtmp_socket.go:759 +0xbe
bbllive/rtmp.(_RtmpNetStream).sendVideo(0xc820362000, 0xc820119170, 0x0, 0x0)
    /data1/go/bbllive/src/bbllive/rtmp/rtmp_netstream.go:324 +0x40c
bbllive/rtmp.(_RtmpNetStream).writeLoop(0xc820362000)
    /data1/go/bbllive/src/bbllive/rtmp/rtmp_netstream.go:200 +0x767
created by bbllive/rtmp.(*DefaultServerHandler).OnPlaying
    /data1/go/bbllive/src/bbllive/rtmp/rtmp_handler.go:79 +0x16e

**Comment by qazmoon** [comment]
@wuli07101  这个东西怎么用？怎么跑起来？

**Comment by gqf2008** [comment]
离开这个行业了，供大家学习考

**Comment by qazmoon** [comment]
去哪个行业了？

**Comment by qazmoon** [comment]
去哪个行业了？

**Comment by qazmoon** [comment]
去哪个行业了？
